changed workflow (#7)
Co-authored-by: Topaz Braverman <topazb@formtitan.com>

diff --git a/.github/workflows/create_ami.yml b/.github/workflows/create_ami.yml
--- a/.github/workflows/create_ami.yml
+++ b/.github/workflows/create_ami.yml
@@ -1,4 +1,4 @@
-name: Validate Inputs and Create AMI
+name: Create AMI
 
 on:
   workflow_dispatch:
@@ -14,14 +14,18 @@ on:
         options:
           - staging
           - production
+      aws_region:
+        description: "AWS Region"
+        required: false
+        default: "eu-central-1"
+      aws_role:
+        description: "AWS Role to assume"
+        required: false
 
 jobs:
   validate-and-create-ami:
-    runs-on: ubuntu-latest
-    env:  # Global environment variables
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      AWS_REGION: us-east-1
+    # Conditional runner selection based on environment input
+    runs-on: ${{ github.event.inputs.environment == 'staging' && 'github-agent-1' || 'production-github-agent-1' }}
 
     steps:
     - name: Checkout repository
@@ -35,6 +39,36 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip boto3
+
+    - name: Set AWS Region and Role based on Environment
+      id: set_env
+      run: |
+        if [ "${{ github.event.inputs.environment }}" == "staging" ]; then
+          echo "AWS Role: arn:aws:iam::034362028102:role/github_oidc_role"
+          echo "AWS Region: eu-central-1"
+          echo "AWS_ROLE=arn:aws:iam::034362028102:role/github_oidc_role" >> $GITHUB_ENV
+          echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV
+        elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
+          echo "AWS Role: arn:aws:iam::327685137044:role/prod_github_oidc_role"
+          echo "AWS Region: eu-central-1"
+          echo "AWS_ROLE=arn:aws:iam::327685137044:role/prod_github_oidc_role" >> $GITHUB_ENV
+          echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV
+        else
+          echo "Error: Unknown environment"
+          exit 1
+        fi
+
+        if [ -n "${{ github.event.inputs.aws_region }}" ]; then
+          echo "Overriding AWS Region to ${{ github.event.inputs.aws_region }}"
+          echo "AWS_REGION=${{ github.event.inputs.aws_region }}" >> $GITHUB_ENV
+        fi
+
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v4.0.2
+      with:
+        role-to-assume: ${{ env.AWS_ROLE }}
+        role-session-name: 'github_to_aws_via_federatedOIDC'
+        aws-region: ${{ env.AWS_REGION }}
 
     - name: Validate Server IP
       id: validate_ip
